/**
 * Backwards-compatible facade.
 *
 * The implementation lives under `src/domain`, `src/infrastructure`, and
 * `src/services/appServices.ts`. UI code can import from this facade while it
 * is progressively migrated to the service module.
 */
export {
  authService,
  clientService,
  paymentService,
  adminSettingsService,
  activityLogService,
  notificationService,
  syncService,
  seedIfNeeded,
  getCurrentUser,
  login,
  logout,
  getAllClients,
  getAllPayments,
  getPaymentSelectableClients,
  getClients,
  getClient,
  getClientReferenceById,
  createClient,
  updateClient,
  deleteClient,
  getPayments,
  getPaymentsByClient,
  createPayment,
  deletePayment,
  getLocalSyncStatus,
  getServerSyncStatus,
  getPaymentNotificationStatusMap,
  getPaymentNotificationStatuses,
  getAdminSettings,
  updateAdminSettings,
  testAdminSmtpEmail,
  getStorageDiagnostics,
  cleanupLegacyLocalStorageData,
  changeLocalDatabaseLocation,
  chooseLocalDatabaseFolder,
  getLocalDatabaseLocation,
  openLocalDatabaseLocation,
  getActivityLogs,
  getNotifications,
  cleanupOldSentNotifications,
  clearSentNotifications,
  getEmployeeAccounts,
  createEmployeeAccount,
  updateEmployeeAccount,
  deleteEmployeeAccount,
  changeCurrentEmployeePassword,
  MAX_EMPLOYEES,
  EMPLOYEE_LIMIT_REACHED_MESSAGE,
  getEmployeeCount,
  hasReachedEmployeeLimit,
  isAdmin,
  isEmployee,
  isSameLocalDay,
  filterForCurrentUserDailyScope,
  isOnline,
  setOnline,
  getLastSync,
  getPendingCount,
  syncPendingData,
  resetDevelopmentTestData,
  formatTND,
  formatDateFR,
  formatDateTimeFR,
} from "@/services/appServices";

export { DEMO_USERS as USERS } from "@/infrastructure/local/authLocalRepository";
